### PR TITLE
Update JWPlayer 

### PR DESCRIPTION
**Pull request by seisvalt**
Update JWPlayer to 7.7.4 version

### CODE REVIEW

**Comment by WadeShuler** [comment]
Please pull the latest version, and resubmit the pull request.

The issue is, you have 2 pull requests. One for the 'sources' check on the 'file' key, and another for updating the JWPlayer version. I already merged your etra check for 'sources' key pull request. So this pull request should not include that commit, and solely by just the updated JWPlayer files.

In the future, please keep your pull requests completely separate by using branches. One issue per pull request.

**Comment by ChrGriffin** [comment]
Hey - don't look at me, I didn't merge these! My only pull request was the 'sources' check.

**Comment by WadeShuler** [comment]
@ChrGriffin You are right. After reading my message again, I was under the impression it was the same person. Didn't notice the name, just assumed since he had your 'source' commit included in his merge.

I am not sure how it happened.

Each pull request should be their own branch, off the master.
`git checkout -b update-774`

[https://help.github.com/articles/creating-a-pull-request/](https://help.github.com/articles/creating-a-pull-request/)

Maybe I should whip up, and look at examples for a CONTRIBUTING file.

**Comment by seisvalt** [comment]
I'm sorry I made a fork from the @ChrGriffin  commit because I was interested in his progress in my project.

**Pull request merged**
